In [18]:
import pandas as pd
import joblib  # or 'import pickle'
import json
import os

In [19]:
# Load the model
MODEL_PATH = './models'

lr_model = joblib.load(os.path.join(MODEL_PATH, 'lr.pkl'))
rf_model = joblib.load(os.path.join(MODEL_PATH, 'rf.pkl'))
xgb_model = joblib.load(os.path.join(MODEL_PATH, 'xgb.pkl'))
lstm_model = joblib.load(os.path.join(MODEL_PATH, 'lstm.pkl'))

In [20]:
# Load your 3 records
TEST_DATA_PATH = './data'

with open(os.path.join(TEST_DATA_PATH, 'test.json'), 'r') as f:
    data = json.load(f)

# Convert JSON to a DataFrame
# (This ensures column names and order match your training data)
test_df = pd.DataFrame(data)

In [21]:
try:
    lr_predictions = lr_model.predict(test_df)  # Get class predictions (0 or 1)
    lr_probs = lr_model.predict_proba(test_df)  # Get probabilities (optional, but helpful for debugging)   

    print("===== LOGISTIC REGRESSION =====")
    print(f"Predictions: {lr_predictions}")
    print(f"Probabilities: \n{lr_probs}")
    print(f"{'='*30}\n")
except Exception as e:
    print(f"Error running Logistic Regression model: {e}")

try:
    rf_predictions = rf_model.predict(test_df)
    rf_probs = rf_model.predict_proba(test_df)

    print("===== RANDOM FOREST =====")
    print(f"Predictions: {rf_predictions}")
    print(f"Probabilities: \n{rf_probs}")
    print(f"{'='*30}\n")
except Exception as e:
    print(f"Error running Random Forest model: {e}")

try:
    xgb_predictions = xgb_model.predict(test_df)
    xgb_probs = xgb_model.predict_proba(test_df)

    print("===== XGBOOST =====")
    print(f"Predictions: {xgb_predictions}")
    print(f"Probabilities: \n{xgb_probs}")
    print(f"{'='*30}\n")
except Exception as e:
    print(f"Error running XGBoost model: {e}")

try:
    lstm_predictions = lstm_model.predict(test_df)
    lstm_probs = lstm_model.predict_proba(test_df)

    print("===== LSTM =====")
    print(f"Predictions: {lstm_predictions}")
    print(f"Probabilities: \n{lstm_probs}")
except Exception as e:
    print(f"Error running LSTM model: {e}")


===== LOGISTIC REGRESSION =====
Predictions: [1 1 1]
Probabilities: 
[[4.30884114e-08 9.99999957e-01]
 [5.28780620e-08 9.99999947e-01]
 [7.20606831e-08 9.99999928e-01]]

===== RANDOM FOREST =====
Predictions: [1 0 1]
Probabilities: 
[[0.13197222 0.86802778]
 [0.83429167 0.16570833]
 [0.16429167 0.83570833]]

===== XGBOOST =====
Predictions: [1 0 1]
Probabilities: 
[[0.00462884 0.99537116]
 [0.88612914 0.11387087]
 [0.006293   0.993707  ]]

Error running LSTM model: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(3, 35), dtype=float32) with name 'input_layer_5' and path ''. Expected shape (None, 7, 4), but input has incompatible shape (3, 35)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(3, 35), dtype=float32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>
